// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/api/:version/graphql.json": {
    params: {
      "version": string;
    };
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/blogs/:blogHandle": {
    params: {
      "blogHandle": string;
    };
  };
  "/collections/accessories": {
    params: {};
  };
  "/collections/tops-shirts": {
    params: {};
  };
  "/collections/outerwear": {
    params: {};
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/authorize": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/collections/pants": {
    params: {};
  };
  "/policies/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/logout": {
    params: {};
  };
  "/collections/all": {
    params: {};
  };
  "/pages/stockists": {
    params: {};
  };
  "/policies": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/discount/:code": {
    params: {
      "code": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/pages/support": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/pages/about": {
    params: {};
  };
  "/llms.txt": {
    params: {};
  };
  "/newsletter": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/account/addresses": {
    params: {};
  };
  "/account/profile": {
    params: {};
  };
  "/account/*": {
    params: {
      "*": string;
    };
  };
  "/search": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/cart/:lines": {
    params: {
      "lines": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blogs/:blogHandle/:articleHandle" | "/api/:version/graphql.json" | "/sitemap/:type/:page.xml" | "/blogs/:blogHandle" | "/collections/accessories" | "/collections/tops-shirts" | "/collections/outerwear" | "/collections/:handle" | "/account/authorize" | "/collections" | "/collections/pants" | "/policies/:handle" | "/products/:handle" | "/account/logout" | "/collections/all" | "/pages/stockists" | "/policies" | "/account/login" | "/discount/:code" | "/sitemap.xml" | "/pages/:handle" | "/pages/support" | "/robots.txt" | "/blogs" | "/pages/about" | "/llms.txt" | "/newsletter" | "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*" | "/search" | "/cart" | "/cart/:lines" | "/*" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/blogs.$blogHandle.$articleHandle.tsx": {
    id: "routes/blogs.$blogHandle.$articleHandle";
    page: "/blogs/:blogHandle/:articleHandle";
  };
  "routes/api.$version.[graphql.json].tsx": {
    id: "routes/api.$version.[graphql.json]";
    page: "/api/:version/graphql.json";
  };
  "routes/sitemap.$type.$page[.xml].tsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/blogs.$blogHandle._index.tsx": {
    id: "routes/blogs.$blogHandle._index";
    page: "/blogs/:blogHandle";
  };
  "routes/collections.accessories.tsx": {
    id: "routes/collections.accessories";
    page: "/collections/accessories";
  };
  "routes/collections.tops-shirts.tsx": {
    id: "routes/collections.tops-shirts";
    page: "/collections/tops-shirts";
  };
  "routes/collections.outerwear.tsx": {
    id: "routes/collections.outerwear";
    page: "/collections/outerwear";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/collections._index.tsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/collections.pants.tsx": {
    id: "routes/collections.pants";
    page: "/collections/pants";
  };
  "routes/policies.$handle.tsx": {
    id: "routes/policies.$handle";
    page: "/policies/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "routes/collections.all.tsx": {
    id: "routes/collections.all";
    page: "/collections/all";
  };
  "routes/pages.stockists.tsx": {
    id: "routes/pages.stockists";
    page: "/pages/stockists";
  };
  "routes/policies._index.tsx": {
    id: "routes/policies._index";
    page: "/policies";
  };
  "routes/account_.login.tsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/discount.$code.tsx": {
    id: "routes/discount.$code";
    page: "/discount/:code";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/pages.support.tsx": {
    id: "routes/pages.support";
    page: "/pages/support";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/blogs._index.tsx": {
    id: "routes/blogs._index";
    page: "/blogs";
  };
  "routes/pages.about.tsx": {
    id: "routes/pages.about";
    page: "/pages/about";
  };
  "routes/[llms.txt].tsx": {
    id: "routes/[llms.txt]";
    page: "/llms.txt";
  };
  "routes/newsletter.tsx": {
    id: "routes/newsletter";
    page: "/newsletter";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*";
  };
  "routes/account.orders._index.tsx": {
    id: "routes/account.orders._index";
    page: "/account/orders";
  };
  "routes/account.orders.$id.tsx": {
    id: "routes/account.orders.$id";
    page: "/account/orders/:id";
  };
  "routes/account.addresses.tsx": {
    id: "routes/account.addresses";
    page: "/account/addresses";
  };
  "routes/account.profile.tsx": {
    id: "routes/account.profile";
    page: "/account/profile";
  };
  "routes/account._index.tsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account.$.tsx": {
    id: "routes/account.$";
    page: "/account/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart" | "/cart/:lines";
  };
  "routes/cart.$lines.tsx": {
    id: "routes/cart.$lines";
    page: "/cart/:lines";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/williamnguyen/afterparty/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/blogs.$blogHandle.$articleHandle": typeof import("./app/routes/blogs.$blogHandle.$articleHandle.tsx");
  "routes/api.$version.[graphql.json]": typeof import("./app/routes/api.$version.[graphql.json].tsx");
  "routes/sitemap.$type.$page[.xml]": typeof import("./app/routes/sitemap.$type.$page[.xml].tsx");
  "routes/blogs.$blogHandle._index": typeof import("./app/routes/blogs.$blogHandle._index.tsx");
  "routes/collections.accessories": typeof import("./app/routes/collections.accessories.tsx");
  "routes/collections.tops-shirts": typeof import("./app/routes/collections.tops-shirts.tsx");
  "routes/collections.outerwear": typeof import("./app/routes/collections.outerwear.tsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.tsx");
  "routes/account_.authorize": typeof import("./app/routes/account_.authorize.tsx");
  "routes/collections._index": typeof import("./app/routes/collections._index.tsx");
  "routes/collections.pants": typeof import("./app/routes/collections.pants.tsx");
  "routes/policies.$handle": typeof import("./app/routes/policies.$handle.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/account_.logout": typeof import("./app/routes/account_.logout.tsx");
  "routes/collections.all": typeof import("./app/routes/collections.all.tsx");
  "routes/pages.stockists": typeof import("./app/routes/pages.stockists.tsx");
  "routes/policies._index": typeof import("./app/routes/policies._index.tsx");
  "routes/account_.login": typeof import("./app/routes/account_.login.tsx");
  "routes/discount.$code": typeof import("./app/routes/discount.$code.tsx");
  "routes/[sitemap.xml]": typeof import("./app/routes/[sitemap.xml].tsx");
  "routes/pages.$handle": typeof import("./app/routes/pages.$handle.tsx");
  "routes/pages.support": typeof import("./app/routes/pages.support.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/blogs._index": typeof import("./app/routes/blogs._index.tsx");
  "routes/pages.about": typeof import("./app/routes/pages.about.tsx");
  "routes/[llms.txt]": typeof import("./app/routes/[llms.txt].tsx");
  "routes/newsletter": typeof import("./app/routes/newsletter.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account.orders._index": typeof import("./app/routes/account.orders._index.tsx");
  "routes/account.orders.$id": typeof import("./app/routes/account.orders.$id.tsx");
  "routes/account.addresses": typeof import("./app/routes/account.addresses.tsx");
  "routes/account.profile": typeof import("./app/routes/account.profile.tsx");
  "routes/account._index": typeof import("./app/routes/account._index.tsx");
  "routes/account.$": typeof import("./app/routes/account.$.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/cart.$lines": typeof import("./app/routes/cart.$lines.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
  "/Users/williamnguyen/afterparty/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};